#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "Robert Poole"
email = "rpoole@workramp.com"

[ui]
editor = "nvim"
diff-formatter = ":git"
pager = ["delta", "--diff-so-fancy"]

[revset-aliases]
local_roots = "roots(mine() & mutable())"
